id: I5890E7B5
ocr_import_info:
  timestamp: '2023-06-28T10:48:28.078888+00:00'
  batch_id: batch-26c6
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 12:03:07.238233+00:00
last_modified: 2023-06-28 12:03:07.238242+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC27
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC27
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་མངོན་པ་མཛོད་ཀྱི་རང་འགྲེལ།  ༼སྟོན་ཆ༽ ༼སྨད་ཆ༽
  languages:
  - bo
  author: སློབ་དཔོན་དབྱིག་གཉེན།
statistics:
  ocr_word_mean_confidence_index: 0.9948720928249645
  ocr_word_median_confidence_index: 1.0
bases:
  I2PD18547:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18547
      total_pages: 388
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD18547.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9946304780235613
  I2PD18546:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18546
      total_pages: 612
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18546.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9950213049210781
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
